<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headLink()->prependStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css');
$this->headLink()->prependStylesheet('https://use.fontawesome.com/releases/v5.8.1/css/all.css');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->prependFile('https://code.jquery.com/jquery-3.3.1.slim.min.js');
$this->headScript()->prependFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js');
$this->headScript()->prependFile('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js');
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();
$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;

$footerLogos = $this->themeSetting('footer_logos');
$footerSponsors = $this->themeSetting('footer_sponsors');
$footerLicense = $this->themeSetting('footer_license');
$footerCitation = $this->themeSetting('footer_citation');
$footerCopyright = $this->themeSetting('footer_copyright');
$footerCols = (!empty($footerLicense) || !empty($footerCitation));
$sponsersCols = !empty($footerSponsors) + !empty($footerLogos);
$socials = $this->themeSetting('social_media');
$socialsExceptions = [
    'social_instagram',
    'social_email',
];
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <header>
            <?php if ($this->themeSetting('logo')): ?>
            <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
            <?php else: ?>
            <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
            <?php endif; ?>
            <div id="search">
                <?php echo $this->partial('common/search-form'); ?>
            </div>

            <nav>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>
        </header>
        <div id="content" role="main">
            <?php echo $this->content; ?>
        </div>
        <footer>
            <!-- Main Row - Ankle -->
            <div id="ankle" class="pt-3 row">

            <!-- Citation and License column -->
            <?php if ($footerLicense || $footerCitation): ?>
                <section id="license-citation-section" class="col-md-<?php echo 4/$footerCols ?>">
                    <div id="license-citation-row" class="row">
                    <?php if ($footerCitation): ?>
                        <div id="citation-col" class="col-12">
                            <h2>Citation</h2>
                            <?php echo $footerCitation; ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($footerLicense): ?>
                        <div id="license-col" class="col-12 pt-3">
                            <h2>Licensing</h2>
                            <?php echo $footerLicense; ?>
                        </div>
                    <?php endif; ?>
                    </div>
                </section>
            <?php endif; ?>

            <!-- Sponsors and Images column -->
            <?php if ($footerSponsors || $footerLogos): ?>
                <section id="logos-sponsors-section" class="col-md-8">
                    <div id="logos-sponsers-row" class="row">
                    <?php if ($footerLogos): ?>
                        <div id="logos-col" class="pt-3 col-lg-<?php echo 12/$sponsersCols ?>">
                            <?php echo $footerLogos; ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($footerSponsors): ?>
                        <div id="sponsors-col" class="col-lg-<?php echo 12/$sponsersCols ?>">
                            <h2>Sponsors</h2>
                            <?php echo $footerSponsors; ?>
                        </div>
                    <?php endif; ?>
                    </div>
                </section>
            <?php endif; ?>

            </div>

            <!-- Copyright and Social - Foot -->
            <hr>
            <div id="foot" class="row">
                <div class="col-md-6 small">
                    <?php echo $footerCopyright; ?>
                </div>
                <div class="col-md-6 text-md-right">
                <?php foreach ($socials as $social): ?>
                    <?php if (in_array($social, $socialsExceptions)) continue; ?>
                    <?php if ($link = $this->themeSetting($social)): ?>
                    <a href="<?php echo $link ?>">
                        <i class="fab fa-<?php echo str_replace('social_', '', $social) ?>-square fa-lg ml-2 mr-2"></i>
                    </a>
                    <?php endif ?>
                <?php endforeach ?>
                <?php if ($link = $this->themeSetting('social_instagram')): ?>
                <a href="<?php echo $link ?>">
                    <i class="fab fa-instagram fa-lg ml-2 mr-2"></i>
                </a>
                <?php endif ?>
                <?php if ($link = $this->themeSetting('social_email')): ?>
                <a href="mailto:<?php echo $link ?>">
                    <i class="fas fa-envelope-square fa-lg ml-2 mr-2"></i>
                </a>
                <?php endif ?>
                </div>
            </div>
        </footer>
    </body>
</html>
